### ISSUE TITLE
Latency Decomposition

### ISSUE THREAD

**Issue by Yzichen** [guochengqian/ASSANet#3]
Thank you very much for your work, but when I tried to use your method I found that the most time consuming in set abstraction is fps and group process, not mlp. This is especially noticeable in the first layer. How to get the results of Latency Decomposition in your paper.

My first layer config is:
input feature channel: 4
npoints: 16384 -> 4096
radius: [0.2, 0.4, 0.8]
nsample: [32, 32, 64]
mlps: [[16,16,32], [16,16,32], [32,32,64]]

**Comment by guochengqian** [comment]
First of all, ours is built upon the MSG variant of PointNet++ not the SSG variant.  We will clarify this in the updated version. 
Second, we consider the latency of the whole architecture not a specific layer. 
Third, the fps will consume more time when the number of points is higher. You can see the trend in our paper (4k points vs 16k).  If you want to use point-based methods for large scale point cloud, you might consider random sampling instead of FPS.
